### ISSUE TITLE
Nop v4.30 Install

### ISSUE THREAD

**Issue by usigirci** [altunbas-huseyin/Nop.Plugin.Payments.MinburPayment#1]
Merhaba,
Çalışma için teşekkürler.
Plugin i yükleyemedim; ekte detayını ilettiğim "BadHttpRequestException: Request body too large." hatası oluşuyor.
Çözüm için bir öneriniz olabilir mi?

[Internal Server Error.pdf](https://github.com/altunbas-huseyin/Nop.Plugin.Payments.MinburPayment/files/5371697/Internal.Server.Error.pdf)

**Comment by altunbas-huseyin** [comment]
Merhabalar;
Sanırım detaylı bir yardıma ihtiyacınız var, minbur.com'dan profesyonel destek alabilirsiniz.

**Comment by usigirci** [comment]
Teşekkürler.
